### ISSUE TITLE
Updating mocks fails

### ISSUE THREAD

**Issue by ghost** [blackberry/MomenticsUnitTestingPlugin#3]
With the message 'The git pull operation on the mocks repository failed." No errors are logged into the console

**Comment by kaikuchn** [comment]
Since no one has answered until now, let me try to give you some pointers on where you might look for solving this problem.

In MocksUnitTestsNavigatorElement.java line 115 to 120

```
   if (git.pullMocks() == false) {
       DialogUtils  .showErrorDialog("Update Mocks Error", "The git pull operation on the mocks repository failed.");
    success[0] = false;
   }
```

So `git.pullMocks()` returned false. `pullMocks()` is defined in GitWrapper.java line 175:

```
    public boolean pullMocks() {
        PullCommand pullCmd = git.pull();
        try {
            PullResult pullResult = pullCmd.call();
            return pullResult.isSuccessful();
        } catch (... lot's of catch statements ...) {
            e.printStackTrace();
        }
        return false;
    }
```

Assuming `pullCmd.call()` didn't throw (if it threw it most likely would've been caught by one of the many catch statements I omitted here. This should be easy to verify though by doing a catch-anything.) then the `pullResult` [was not successful](http://download.eclipse.org/jgit/docs/jgit-3.0.0.201306101825-r/apidocs/org/eclipse/jgit/api/PullResult.html#isSuccessful%28%29).

I don't know why it would not be successful without throwing. You'd have to look into the docs of the pullCmd for that. Maybe it is possible that the repository just wasn't opened? See `GitWrapper.java` line 57:

```
    public static GitWrapper openRepository(String path) {
        GitWrapper gitWrapper = new GitWrapper();
        File repoDir = new File(path + "/.git");
        if (repoDir.exists()) {
            try {
                gitWrapper.git = Git.open(repoDir);
                return gitWrapper;
            } catch (NoWorkTreeException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        return null;
    }
```

So if the directory doesn't exist you don't get any error but a null pointer returned. The directory is specified here: `MocksUnitTestsNavigatorElement.java` line 141

```
    private GitWrapper getGitWrapper() {
        String path = this.getProject().getFolder("/unittests/bbmocks")
                .getLocation().toString();
        GitWrapper gitWrapper = GitWrapper.openRepository(path);
        return gitWrapper;
    }
```

My best guess is that the repo path is just wrong. Hope this helps!

**Comment by ghost** [comment]
Thanks!
